---
- name: ensure required package with api
  apt:
    pkg:
    - mininet
    - python-pip

- name: pip install with shell
  shell: |
    pip install ipaddr
    pip install "pytest<5"
    pip install exabgp==3.4.17
    useradd -d /var/run/exabgp/ -s /bin/false exabgp

    apt-get install gdb -y
    systemctl stop apport.service
    systemctl disable apport.service

- name: update /etc/security/limits.conf
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      *               soft    core          unlimited
      root            soft    core          unlimited
      *               hard    core          unlimited
      root            hard    core          unlimited

- name: package install for build
  shell: |
    apt update -y
    apt-get -y install \
      git autoconf automake libtool make libreadline-dev texinfo \
      pkg-config libpam0g-dev libjson-c-dev bison flex python3-pytest \
      libc-ares-dev python3-dev libsystemd-dev python-ipaddress python3-sphinx \
      install-info build-essential libsystemd-dev libsnmp-dev perl libcap-dev

    cd /tmp
    wget https://ci1.netdef.org/artifact/LIBYANG-LY1REL/shared/build-4/Ubuntu-20.04-x86_64-Packages/libyang-dev_1.0.184-4-gf0cf7120-1~1.gbp1b59fa_amd64.deb
    wget https://ci1.netdef.org/artifact/LIBYANG-LY1REL/shared/build-4/Ubuntu-20.04-x86_64-Packages/libyang1_1.0.184-4-gf0cf7120-1~1.gbp1b59fa_amd64.deb
    apt install -y ./*.deb

- name: add user for frr
  shell: |
    groupadd -r -g 92 frr
    groupadd -r -g 85 frrvty
    adduser --system --ingroup frr --home /var/run/frr/ \
       --gecos "FRR suite" --shell /sbin/nologin frr
    usermod -a -G frrvty frr

- name: ensure extra-virtual
  shell: |
    apt install -y linux-image-extra-virtual
