---
all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_common_args: " -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    vms:
    # - name: 'ubuntu-1804-amd64'
    #   mac:  '52:54:00:11:11:11'
    #   ip:   '192.168.133.11'
    #   disk: '16G'
    #   ram:  '128000'
    #   vcpu: '16'
    #   os_variant: 'ubuntu18.04'
    #   image_name: '/var/lib/libvirt/images/ubuntu-1804-amd64.img'
    #   cdrom: '/var/lib/libvirt/images/base-ubuntu-1804-amd64-cidata.iso'
    #   cloud_image_dst: '/var/lib/libvirt/images/cloud-ubuntu-1804-amd64.img'
    #   cloud_image_url: 'https://cloud-images.ubuntu.com/bionic/20201211.1/bionic-server-cloudimg-amd64.img'
    #   cloud_image_sum: 'sha256:f136639410c31008a49c57ea8963923773d0cafe2834c7e59a8dacd326c640f3'
    - name: 'ubuntu-1604-amd64'
      mac:  '52:54:00:12:12:12'
      ip:   '192.168.133.12'
      disk: '16G'
      ram:  '8000'
      vcpu: '4'
      os_variant: 'ubuntu16.04'
      image_name: '/var/lib/libvirt/images/ubuntu-1604-amd64.img'
      cdrom: '/var/lib/libvirt/images/base-ubuntu-1604-amd64-cidata.iso'
      cloud_image_dst: '/var/lib/libvirt/images/cloud-ubuntu-1604-amd64.img'
      cloud_image_url: 'https://cloud-images.ubuntu.com/xenial/20201202.1/xenial-server-cloudimg-amd64-disk1.img'
      cloud_image_sum: 'sha256:66d53a80bcd7c7193b6f7ec83ff0e67ff77420cbf7af4c26009918fd34f49749'
vm:
  hosts:
    # 192.168.133.11:
    192.168.133.12:

