---
- hosts: localhost
  become: True
  become_method: sudo
  gather_facts: no
  roles:
  - libvirt
  - os_installer
  - vm

- hosts: vm
  become: True
  become_method: sudo
  gather_facts: yes
  roles:
  - iproute2
