---
- hosts: localhost
  become: True
  become_method: sudo
  gather_facts: True
  tasks:

  - name: install required packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - libguestfs
      - libvirt
      - libvirt-client
      - virt-manager
      - virt-top
      - virt-viewer
      - virt-who
      - virt-install
      - bridge-utils
      - qemu-kvm
      - qemu-system-x86

  - name: vm.xml
    template:
      src: vm.xml
      dest: /tmp/vm.xml
    vars:
      name: slankdev

  - name: rmmod kvm
    modprobe:
      name: kvm_intel
      state: absent
    ignore_errors: True

  - name: insmod kvm
    modprobe:
      name: kvm_intel
      state: present
      params:
        nested: "1"

  - name: enable and start libvirtd
    systemd:
      name: libvirtd
      state: restarted
      enabled: yes
