---
- hosts: localhost
  become: True
  become_method: sudo
  gather_facts: True
  tasks:

  - name: install required packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - libguestfs
      - libvirt
      - libvirt-client
      - virt-manager
      - virt-top
      - virt-viewer
      - virt-who
      - virt-install
      - bridge-utils
      - qemu-kvm
      - qemu-system-x86

  - name: rmmod kvm
    modprobe:
      name: kvm_intel
      state: absent
    ignore_errors: True

  - name: insmod kvm
    modprobe:
      name: kvm_intel
      state: present
      params:
        nested: "1"

  - name: enable and start libvirtd
    systemd:
      name: libvirtd
      state: restarted
      enabled: yes

  - name: get ubuntu-1604-i386 cloud image
    get_url:
      url: https://cloud-images.ubuntu.com/xenial/20200814/xenial-server-cloudimg-i386-disk1.img
      dest: /tmp/ubuntu-1604-i386.img
      checksum: sha256:6f029ff24448dbceae156d0a52456709c51504a77f3f89ebf41fc75c656f875a

  - name: copy vm image
    copy:
      src: /tmp/ubuntu-1604-i386.img
      dest: /var/lib/libvirt/images/ubuntu1604-i386.img
      owner: qemu
      group: qemu
      mode: 0600
      force: no

  - name: vm.xml
    virt:
      command: define
      xml: "{{ lookup('template', 'domain.xml.j2') }}"
    vars:
      name: ubuntu-1604-i386
      image: /var/lib/libvirt/images/ubuntu1604-i386.img
