- name: set authorized key
  become: no
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/fdk.pub"
