---
- name: shell2
  with_items: '{{ vms }}'
  shell: |
    set -uxe
    if [ -e {{ item.image_name }} ]; then
      exit
    fi

    qemu-img create -f qcow2 \
      -o backing_file={{ item.cloud_image_dst }} \
      {{ item.image_name }}
    qemu-img resize {{ item.image_name }} {{ item.disk }}

    virt-install \
      --connect qemu:///system \
      --virt-type kvm \
      --name {{ item.name }} \
      --ram {{ item.ram }} --vcpus={{ item.vcpu }} \
      --os-type linux \
      --os-variant {{ item.os_variant }} \
      --disk path={{ item.image_name }},format=qcow2 \
      --disk {{ item.cdrom }},device=cdrom \
      --import --network network=fdk,mac={{ item.mac }} \
      --noautoconsole

- name: wait sshd is launched
  wait_for:
    host: "{{ item.ip }}"
    port: 22
    timeout: 120
  with_items: '{{ vms }}'
